process rotate
codigician/tetris pull request #11
Opened 2022-10-26 15:14 UTC by yigittan

2022-10-27 21:34 UTC, bilginyuksel requested changes

2022-10-27 21:34 UTC, bilginyuksel commented on deneme.py
> +rotated_shape = []
We should delete this file

2022-10-27 21:34 UTC, bilginyuksel commented on src/grid.py
> +from shape import Shape, create_shape
Probably we are not using this import we should delete create shape from imports

2022-10-27 21:34 UTC, bilginyuksel commented on src/shape.py
> +    shape.units = []
Biz yeni bir shape yaratmak istiyoruz parametre aldigimizi degistirmek degil o yuzden burada yeni bir shape yaratmamiz lazim

2022-10-27 21:43 UTC, yigittan commented on src/shape.py
> +    shape.units = []
aradaki fark nedir ? eski shape kullanılmıcaksa bunun ne zararı var ?

2022-10-28 14:54 UTC, bilginyuksel commented on src/shape.py
> +    shape.units = []
mesela gridde bu shape relocate yapilirken eski shape yerini degistirirsen silecegin sekilleri kaybetmis olucaksin

2022-10-28 14:54 UTC, bilginyuksel commented on src/shape.py
> +    """
bunu silelim bence testlerde zaten var bunlar

2022-10-28 14:54 UTC, bilginyuksel commented on src/shape.py
> +    second_grid = [[None for _ in range(dimension)] for _ in range(dimension)]
Bu tarz bir isim versek daha anlamli olabilir bunun icin
```suggestion
    rotated_grid = [[None for _ in range(dimension)] for _ in range(dimension)]
```

2022-10-28 14:54 UTC, bilginyuksel commented on src/shape.py
> +    dimension = max(row_diff, col_diff)
max ve mini surekli ic ice yazmaktansa birer degiskene atayipda yapabiliriz asagiya bir tane ornek birakiyorum

```suggestion
    unit_rows = [unit.row for unit in shape.units]
    unit_cols = [unit.col for unit in shape.units]
    
    max_row, min_row = max(unit_rows), min(unit_rows)
    max_col, min_col = max(unit_cols), min(unit_cols)

    row_diff = max_row - min_row + 1
    col_diff = max_col - min_col + 1
    min_value = min(min_col, min_row)
    dimension = max(row_diff, col_diff)
```

2022-10-28 14:54 UTC, bilginyuksel commented on src/shape.py
> +    """
bunu silebilirz bence ne dusunuyorsun

2022-10-28 14:54 UTC, bilginyuksel commented on src/shape.py
> +    new_shape = Shape(0, 0)
Isimlendirmeyi asagidaki gibi yapabiliriz ne dusunyorsun?
```suggestion
    rotated_shape = Shape(0, 0)
```

2022-10-28 14:54 UTC, bilginyuksel commented on src/shape.py
> +            if second_grid[row][col] != None:
None icin `!=` gibi mantiksal operatorler yerine direkt `is not None` veya direkt `if second_grid[row][col]` yazabiliriz cunku bu ifade `None` degilse devam etmek istiyorsun. Mesela `None` oldugunda devam etmek isteseydin `if not second_grid[row][col]` yazilabilirdi.

```suggestion
            if second_grid[row][col] is not None:
```

2022-10-28 14:54 UTC, bilginyuksel commented on test/test_shape.py
> +    - - - U -
burada bu matrislerin buyuklugu sasirtici olmus bunlarida `3x3` yapabiliriz

2022-10-28 14:54 UTC, bilginyuksel commented on test/test_shape.py
> +    - - - - U
matris buyuklukleri fazla olmus buradada

2022-10-28 14:54 UTC, bilginyuksel commented on test/test_shape.py
> +   U - - -
bunun tabini duzeltebilriz

2022-10-28 15:15 UTC, bilginyuksel approved these changes

2022-10-28 15:15 UTC, bilginyuksel commented on src/shape.py
> +    """
```suggestion
```

2022-10-28 15:27 UTC, merged